name: Build APK

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: Bubblewrap/buildozer-action@v1
      with:
        image: kivy/buildozer:latest
        command: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: FitnesApp-${{ steps.get-date.outputs.date }}
        path: bin/*.apk
